# Generated by Django 4.2.5 on 2024-06-23 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('profile_desc', models.TextField()),
                ('followers_list', models.BinaryField()),
                ('following_list', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=300)),
                ('post_picture', models.ImageField(blank=True, null=True, upload_to='post_pic')),
                ('post_description', models.TextField()),
                ('is_image_post', models.BooleanField(default=False)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('no_of_comments', models.IntegerField(default=0)),
                ('liked_by_current_user', models.BooleanField(default=False)),
                ('list_of_user_liked_the_post', models.BinaryField()),
                ('created_at', models.DateTimeField()),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('commented_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commented_by_user', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_app.post')),
                ('replied_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replied_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
